services:
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: "ep_db_user"
      POSTGRES_DB: "ep_db"
    volumes:
      - ./db-data:/var/lib/postgresql/data
